import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import { IsInt, Min, Max, IsArray, IsOptional } from 'class-validator';
import { Type } from 'class-transformer';

export class GenerateSecurityScheduleDto {
  @ApiProperty({
    description: 'Year to generate the schedule for',
    example: 2026,
    minimum: 1900,
    maximum: 3000,
  })
  @IsInt({ message: 'Year must be an integer' })
  @Min(1900)
  @Max(3000)
  @Type(() => Number)
  year: number;

  @ApiProperty({
    description: 'Month to generate the schedule for (1-12)',
    example: 9,
    minimum: 1,
    maximum: 12,
  })
  @IsInt({ message: 'Month must be an integer' })
  @Min(1)
  @Max(12)
  @Type(() => Number)
  month: number;

  @ApiPropertyOptional({
    description:
      'Optional custom shift pairs (teams of 2 employee ids). When provided, ' +
      'the month is generated by rotating these pairs through Pagi/Malam/off ' +
      'each day (Pagi=pairs[d%n], Malam=pairs[(d+1)%n]). When omitted, falls ' +
      'back to the fair individual rotation.',
    example: [
      ['550e8400-e29b-41d4-a716-446655440000', '660e8400-e29b-41d4-a716-446655440000'],
      ['770e8400-e29b-41d4-a716-446655440000', '880e8400-e29b-41d4-a716-446655440000'],
    ],
  })
  @IsOptional()
  @IsArray()
  @IsArray({ each: true, message: 'Setiap pasangan harus berupa array [idA, idB]' })
  pairs?: string[][];
}
